version: "3"

volumes:
  db_data: {}

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'lightninglottery'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'lightninglottery'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'lightninglottery'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'lightninglottery'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql