version: "3"

volumes:
  db_data: {}

services:

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'lightninglottery'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'lightninglottery'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'lightninglottery'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'lightninglottery'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backendServer:
    image: bitcoinslovenia/lightningloterry:latest
    container_name: lightningLoterryBackend
    depends_on:
        - db
    restart: always
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/lightninglottery?useUnicode=true&characterEncoding=utf8&useSSL=false'
      - 'SPRING_DATASOURCE_USERNAME=lightninglottery'
      - 'SPRING_DATASOURCE_PASSWORD=lightninglottery'
      - 'SPRING_FLYWAY_ENABLED=false'
    ports:
      - '8080:8080'